Models/Book.cs
using System.ComponentModel.DataAnnotations;

namespace RSWEBBookShop.Models
{
    public class Book
    {
        public int Id { get; set; }

        [StringLength(100)]
        [Required]
        public string Title { get; set; }

        [Display(Name = "Year Published")]
        public int? YearPublished { get; set; }

        [Display(Name = "Number of pages")]
        public int? NumPages { get; set; }
        public string? Description { get; set; }

        [StringLength(50)]
        public string? Publisher { get; set; }
        public string? FrontPage { get; set; }

        [Display(Name = "Download URL")]
        public string? DownloadUrl { get; set; }

        [Display(Name = "Author")]
        public int AuthorId { get; set; }
        public Author? Author { get; set; }
        public ICollection<BookGenre>? Genres { get; set; }
        public ICollection<Review>? Reviews { get; set; }
        public ICollection<UserBook>? Users { get; set; }

    }
}

Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RSWEBBookShop.Data;
using RSWEBBookShop.Models;
using RSWEBBookShop.ViewModels;

namespace RSWEBBookShop.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly RSWEBBookShopContext _context;

        public AuthorsController(RSWEBBookShopContext context)
        {
            _context = context;
        }

        // GET: Authors
        public async Task<IActionResult> Index(string authorNat, string searchString)
        {
            IQueryable<Author> authors = _context.Author.AsQueryable();
            IQueryable<string>? natQuery = _context.Author.OrderBy(m => m.Nationality).Select(m => m.Nationality).Distinct();

            if (!string.IsNullOrEmpty(searchString))
            {
                authors = authors.Where(a => a.FirstName.Contains(searchString)  || a.LastName.Contains(searchString));
                //authors = authors.Where(a => a.FullName.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(authorNat))
            {
                authors = authors.Where(n => n.Nationality == authorNat);
            }
            var authorNatVM = new AuthorNationalityViewModel
            {
                Nationalities = new SelectList(await natQuery.ToListAsync()),
                Authors = await authors.ToListAsync()
            };
            return View(authorNatVM);
        }

        // GET: Authors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Author == null)
            {
                return NotFound();
            }
            var mVCBookContext = _context.Author.Include(m => m.Books);
            var author = await _context.Author
                .Include(a=>a.Books)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // GET: Authors/Create
        //[Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,BirthDate,Nationality,Gender")] Author author)
        {
            if (ModelState.IsValid)
            {
                _context.Add(author);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Edit/5
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Author == null)
            {
                return NotFound();
            }

            var author = await _context.Author.FindAsync(id);
            if (author == null)
            {
                return NotFound();
            }
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,BirthDate,Nationality,Gender")] Author author)
        {
            if (id != author.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(author);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AuthorExists(author.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Author == null)
            {
                return NotFound();
            }

            var author = await _context.Author
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Author == null)
            {
                return Problem("Entity set 'RSWEBBookShopContext.Author'  is null.");
            }
            var author = await _context.Author.FindAsync(id);
            if (author != null)
            {
                _context.Author.Remove(author);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AuthorExists(int id)
        {
          return (_context.Author?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RSWEBBookShop.Data;
using RSWEBBookShop.Interfaces;
using RSWEBBookShop.Models;
using RSWEBBookShop.ViewModels;

namespace RSWEBBookShop.Controllers
{
    public class BooksController : Controller
    {
        private readonly RSWEBBookShopContext _context;
        readonly IBufferedFileUploadService _bufferedFileUploadService;
        readonly IStreamFileUploadService _streamFileUploadService;
        private IWebHostEnvironment Environment;

        public BooksController(RSWEBBookShopContext context, IBufferedFileUploadService bufferedFileUploadService, IStreamFileUploadService streamFileUploadService, IWebHostEnvironment environment)
        {
            _context = context;
            _bufferedFileUploadService = bufferedFileUploadService;
            _streamFileUploadService= streamFileUploadService;
            Environment = environment;
        }

        // GET: Books
        public async Task<IActionResult> Index(string searchString)
        {
            IQueryable<Book> books = _context.Book.AsQueryable();
            //IQueryable<string> genreQuery = (IQueryable<string>)_context.Book.OrderBy(b => b.Genres).Select(b => b.Genres).Distinct();

            if (!string.IsNullOrEmpty(searchString))
            {
                books = books.Where(s => s.Title.Contains(searchString));
            }
            books = books
                .Include(b => b.Author)
                .Include(b => b.Reviews);

            var bookGenreVM = new BookGenreViewModel
            {
                //Genres = new SelectList(await genreQuery.ToListAsync()),
                Books = await books.ToListAsync()
            };
            return View(bookGenreVM);
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Book == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .Include(b => b.Author)
                .Include(b=>b.Reviews)
                .Include(b=>b.Genres)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        public async Task<IActionResult> DownloadFile(string url)
        {
            var filePaths = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Files/" + url);
            var memory = new MemoryStream();
            using (var stream = new FileStream(filePaths, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;
            return File(memory, "application/pdf");
        }

        // GET: Books/Create
        //[Authorize(Roles="Admin")]
        public IActionResult Create()
        {
            ViewData["AuthorId"] = new SelectList(_context.Author, "Id", "FullName");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(IFormFile pic, IFormFile pdf,[Bind("Id,Title,YearPublished,NumPages,Description,Publisher,FrontPage,DownloadUrl,AuthorId")] Book book)
        {
            ModelState.Remove("file");

            if (ModelState.IsValid)
            {
                try
                {
                    book.FrontPage = await _bufferedFileUploadService.UploadFile(pic);
                    book.DownloadUrl = await _bufferedFileUploadService.UploadFile(pdf);
                    if (!string.IsNullOrEmpty(book.FrontPage) && !string.IsNullOrEmpty(book.DownloadUrl))
                    {
                        ViewBag.Message = "File Upload Successful";
                    }
                    else
                    {
                        ViewBag.Message = "File Upload Failed";
                    }
                }
                catch (Exception ex)
                {
                    //Log ex
                    ViewBag.Message = "File Upload Failed";
                }
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Author, "Id", "FullName", book.AuthorId);
            return View(book);


            //if (ModelState.IsValid)
            //{
            //    _context.Add(book);
            //    await _context.SaveChangesAsync();
            //    return RedirectToAction(nameof(Index));
            //}
            //ViewData["AuthorId"] = new SelectList(_context.Set<Author>(), "Id", "FullName", book.AuthorId);
            //return View(book);
        }

        // GET: Books/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Book == null)
            {
                return NotFound();
            }

            var book = _context.Book.Where(b => b.Id == id)
                .Include(b => b.Genres).First();
            if (book == null)
            {
                return NotFound();
            }
            var genres = _context.Genre.AsEnumerable();
            genres = genres.OrderBy(s => s.GenreName);

            BookGenresEditViewModel viewmodel = new BookGenresEditViewModel
            {
                Book = book,
                GenresList = new MultiSelectList(genres, "Id", "GenreName"),
                SelectedGenres = book.Genres.Select(sg => sg.GenreId)
            };
            ViewData["AuthorId"] = new SelectList(_context.Author, "Id", "FirstName", book.AuthorId);
            return View(viewmodel);
            //ViewData["AuthorId"] = new SelectList(_context.Set<Author>(), "Id", "FirstName", book.AuthorId);
            //return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, BookGenresEditViewModel viewModel)
        {
            if (id != viewModel.Book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(viewModel.Book);
                    await _context.SaveChangesAsync();

                    IEnumerable<int> newGenreList = viewModel.SelectedGenres;
                    IEnumerable<int> prevGenreList = _context.BookGenre.Where(s => s.BookId == id).Select(s => s.GenreId);
                    IQueryable<BookGenre> toBeRemoved = _context.BookGenre.Where(s => s.BookId == id);
                    if (newGenreList != null)
                    {
                        toBeRemoved = toBeRemoved.Where(s => !newGenreList.Contains(s.GenreId));
                        foreach (int genreId in newGenreList)
                        {
                            if (!prevGenreList.Any(s => s == genreId))
                            {
                                _context.BookGenre.Add(new BookGenre { GenreId = genreId, BookId = id });
                            }
                        }
                    }
                    _context.BookGenre.RemoveRange(toBeRemoved);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(viewModel.Book.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Author, "Id", "FirstName", viewModel.Book.AuthorId);
            return View(viewModel);

        }

        // GET: Books/Delete/5
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Book == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .Include(b => b.Author)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Book == null)
            {
                return Problem("Entity set 'RSWEBBookShopContext.Book'  is null.");
            }
            var book = await _context.Book.FindAsync(id);
            if (book != null)
            {
                _context.Book.Remove(book);
            }
            
            await _context.SaveChangesAsync();

Views/Books/Create.cshtml
@model RSWEBBookShop.Models.Book

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearPublished" class="control-label"></label>
                <input asp-for="YearPublished" class="form-control" />
                <span asp-validation-for="YearPublished" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumPages" class="control-label"></label>
                <input asp-for="NumPages" class="form-control" />
                <span asp-validation-for="NumPages" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Publisher" class="control-label"></label>
                <input asp-for="Publisher" class="form-control" />
                <span asp-validation-for="Publisher" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FrontPage" class="control-label"></label>
                <div class="col-md-10">
                    <input type="file" name="pic" asp-for="FrontPage" class="form-control" />
                </div>
                <!-- <input asp-for="FrontPage" class="form-control" /> -->
                <span asp-validation-for="FrontPage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DownloadUrl" class="control-label"></label>
                <div class="col-md-10">
                    <input type="file" name="pdf" asp-for="DownloadUrl" class="form-control" />
                </div>
                <span asp-validation-for="DownloadUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorId" class="control-label"></label>
                <select asp-for="AuthorId" class ="form-control" asp-items="ViewBag.AuthorId">
                    <option value="">Select</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Books/Delete.cshtml
@model RSWEBBookShop.Models.Book

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.YearPublished)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.YearPublished)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumPages)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumPages)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Publisher)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FrontPage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FrontPage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DownloadUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DownloadUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author.FullName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Books/Details.cshtml
@model RSWEBBookShop.Models.Book

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.YearPublished)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.YearPublished)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumPages)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumPages)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Publisher)
        </dd>
        @if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
        {
            <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DownloadUrl)
        </dt>
        <dd class="col-sm-10">
            <form a asp-action="DownloadFile" asp-controller="Books" class="col-sm-10" target="_blank">
                <input name="url" type="hidden" value="@Model.DownloadUrl" />
                <input type="submit" value="Download Here" />
            </form>
        </dd>
        }
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            <a asp-controller="Authors" asp-action="Details" asp-route-id="@Model.Author.Id">
                @Model.Author.FullName
            </a> <br />
        </dd>
    </dl>
    <div>
        <h5>Reviews</h5>
        <hr />
        @foreach (var review in Model.Reviews)
        {
            <h6>@review.AppUser</h6>
            <p>@review.Comment</p>
        }
    </div>
</div>
<div>
    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
    {
        <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a>
    }
    |
    <a asp-action="Index">Back to List</a>
</div>

Views/Books/Index.cshtml
@model RSWEBBookShop.ViewModels.BookGenreViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
   <p>
     <a asp-action="Create">Create New</a>
   </p> 
}

<form asp-controller="Books" asp-action="Index" method="get">
    <p>
        Title: <input type="text" asp-for="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            @foreach (var item in Model.Books)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="@item.FrontPage" href="@item.FrontPage" width="50" height="300">
                        <div class="card-body">
                            <h2 class="card-text">@item.Title</h2>
                            <h5 class="card-text">
                                <a asp-controller="Authors" asp-action="Details" asp-route-id="@item.Author?.Id">
                                    @item.Author?.FullName
                                </a>
                            </h5>
                            <p class="card-text"> @item.YearPublished</p>
                            <p class="card-text">
                                Average rating:
                                @{
                                    var avg = item.Reviews?.Count > 0 ? item.Reviews.Average(r => r.Rating) : 0;
                                    @String.Format("{0:0.00}",avg)
                                    ;
                                }
                            </p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <td>       
                                        @if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                        {
                                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                                        }
                                        |
                                        <a asp-action="Details" asp-route-id="@item.Id">Details</a>|
                                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                        {
                                           <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> 
                                        }
                                    </td>
                                </div>
                                <small class="text-muted">9 mins</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@*<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.YearPublished)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumPages)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Publisher)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FrontPage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DownloadUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.YearPublished)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumPages)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Publisher)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FrontPage)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DownloadUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author.FullName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>*@